framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: 'digikala_cc:'

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: redis://localhost:6379
#
        pools:
          app.cache.search:
              name: app.cache.search
              public: true
              adapter: cache.app
              default_lifetime: 3600 # 1 hour

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
